export const items = [
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
  {
    photo: 'car_1.jpg',
    name: 'Buick LaCrosse',
    price: '389.00',
    luggage: 8,
    doors: 4,
    passenger: 4,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam',
  },
]
